### ISSUE TITLE
License, Citation, Attribution?

### ISSUE THREAD

**Issue by dlaehnemann** [au-phiware/bankers#1]
Hi Corin,

as I couldn't find a license or attribution statement in your code, I just wanted to check in, if you wanted anything beyond an attribution to you (and Eric Burnett) when using your banker's sequence code?

Best regards,
David

P.S.: Sorry for misusing the Issues system, but I couldn't find any eMail address to contact you. The reCaptcha for contacting you via phiware.com.au seems broken.

**Comment by au-phiware** [comment]
Sorry, I only just saw this! I've licensed the code under the MIT license. Enjoy!

I am curious to know how you have found this project useful :)

**Comment by dlaehnemann** [comment]
Hi Corin,

good to hear from you. I have used the banker's sequence code for a plugin to a bioinformatics toolkit that deals with genetic variation data. To me, the banker's sequence just seemed like an intuitive sort order for enumerating all possible subsets where it is easy to find a particular subset in the mere list and at the same time it is well-defined and thus allows for effective indexing into a corresponding array to store information regarding every possible subset. You can check out the code usage (and adaptations) here:
https://github.com/samtools/bcftools/blob/develop/plugins/GTisec.c
https://github.com/dlaehnemann/bankers2/blob/master/bankers2VennDiagram.c
https://github.com/dlaehnemann/bankers2/blob/master/bankers2circos.c

And examples of the visualisations that I used it for, with the bankers2 scripts, are in the respective repository:
https://github.com/dlaehnemann/bankers2

Thanks again for having created this code, it saved me some work! And I figure I should include the copyright notice in all instances, then?

Best regards,
David
